---
- name: Configure FRR
  when: (enable_frr is defined) and (enable_frr | bool)
  block:
    - name: Remove FRR configuration files if they exist
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "10-private.netdev"
        - "11-public.netdev"
        - "20-private.network"
        - "21-public.network"

    - name: Add FRR private interface
      ansible.builtin.blockinfile:
        path: /etc/systemd/network/10-private.netdev
        block: |
          [NetDev]
          Name=private
          Kind=dummy
        state: present
        mode: '644'
        create: true

    - name: Add FRR public interface
      ansible.builtin.blockinfile:
        path: /etc/systemd/network/11-public.netdev
        block: |
          [NetDev]
          Name=public
          Kind=dummy
        state: present
        mode: '644'
        create: true

    - name: Add FRR private interface address
      ansible.builtin.blockinfile:
        path: /etc/systemd/network/20-private.network
        block: |
          [Match]
          Name=private

          [Network]
          Address={{ kolla_internal_vip_address }}/32
        state: present
        mode: '644'
        create: true

    - name: Add FRR public interface address
      ansible.builtin.blockinfile:
        path: /etc/systemd/network/21-public.network
        block: |
          [Match]
          Name=public

          [Network]
          Address={{ kolla_external_vip_address }}/32
        state: present
        mode: '644'
        create: true

    - name: Restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted
        enabled: true
      ignore_errors: true
      register: systemd_networkd_restart
